apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
  namespace: project2
spec:
  selector:
    app: banking-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: project2
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306